[package]
name = "gerasdb"
version = "0.0.0-dev"
authors = ["i5heu <i5h@i5h.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2_sqlite = "0.16.0" 
r2d2 = "0.8.9"
rusqlite = "0.23.1"
